// Stage 3 execution: dual even/odd lanes (RV32I scalar + 128-bit SIMD).
module s3_execution
  import spu_lite_pkg::*;
(
  input  logic        even_valid,
  input  logic [6:0]  even_opcode,
  input  logic [2:0]  even_funct3,
  input  logic [6:0]  even_funct7,
  input  logic [4:0]  even_rd,
  input  logic [31:0] even_rs1_data,
  input  logic [31:0] even_rs2_data,
  input  logic [31:0] even_imm,
  input  logic [31:0] even_pc,
  input  vreg_t       even_vs1_data,
  input  vreg_t       even_vs2_data,

  input  logic        odd_valid,
  input  logic [6:0]  odd_opcode,
  input  logic [2:0]  odd_funct3,
  input  logic [4:0]  odd_rd,
  input  logic [31:0] odd_rs1_data,
  input  logic [31:0] odd_rs2_data,
  input  logic [31:0] odd_imm,
  input  logic [31:0] odd_pc,
  input  vreg_t       odd_vs_data,

  output logic        even_reg_write,
  output logic [4:0]  even_rd_out,
  output logic [31:0] even_alu_result,
  output logic [31:0] even_wb_data,
  output logic        even_vreg_write,
  output logic [2:0]  even_vd_out,
  output vreg_t       even_vreg_result,

  output logic        odd_branch_taken,
  output logic [31:0] odd_branch_target,
  output logic        odd_jump,
  output logic [31:0] odd_jump_target,
  output logic        odd_mem_read,
  output logic        odd_mem_write,
  output logic [31:0] odd_mem_addr,
  output logic [31:0] odd_mem_wdata,
  output logic [3:0]  odd_mem_be,
  output logic        odd_reg_write,
  output logic [4:0]  odd_rd_out,
  output logic [31:0] odd_link_data,
  output logic        odd_vec_mem_read,
  output logic        odd_vec_mem_write,
  output logic [31:0] odd_vec_mem_addr,
  output logic [15:0] odd_vec_mem_be,
  output vreg_t       odd_vec_mem_wdata,
  output logic        odd_vreg_write,
  output logic [2:0]  odd_vd_out,
  output logic        odd_vec_addr_misaligned
);

  even_lane u_even (
    .valid        (even_valid),
    .opcode       (even_opcode),
    .funct3       (even_funct3),
    .funct7       (even_funct7),
    .rd           (even_rd),
    .rs1_data     (even_rs1_data),
    .rs2_data     (even_rs2_data),
    .imm          (even_imm),
    .pc           (even_pc),
    .vs1_data     (even_vs1_data),
    .vs2_data     (even_vs2_data),
    .reg_write    (even_reg_write),
    .rd_out       (even_rd_out),
    .alu_result   (even_alu_result),
    .wb_data      (even_wb_data),
    .vreg_write   (even_vreg_write),
    .vd_out       (even_vd_out),
    .vreg_result  (even_vreg_result)
  );

  odd_lane u_odd (
    .valid               (odd_valid),
    .opcode              (odd_opcode),
    .funct3              (odd_funct3),
    .rd                  (odd_rd),
    .rs1_data            (odd_rs1_data),
    .rs2_data            (odd_rs2_data),
    .imm                 (odd_imm),
    .pc                  (odd_pc),
    .vs_data             (odd_vs_data),
    .branch_taken        (odd_branch_taken),
    .branch_target       (odd_branch_target),
    .jump                (odd_jump),
    .jump_target         (odd_jump_target),
    .mem_read            (odd_mem_read),
    .mem_write           (odd_mem_write),
    .mem_addr            (odd_mem_addr),
    .mem_wdata           (odd_mem_wdata),
    .mem_be              (odd_mem_be),
    .reg_write           (odd_reg_write),
    .rd_out              (odd_rd_out),
    .link_data           (odd_link_data),
    .vec_mem_read        (odd_vec_mem_read),
    .vec_mem_write       (odd_vec_mem_write),
    .vec_mem_addr        (odd_vec_mem_addr),
    .vec_mem_be          (odd_vec_mem_be),
    .vec_mem_wdata       (odd_vec_mem_wdata),
    .vreg_write          (odd_vreg_write),
    .vd_out              (odd_vd_out),
    .vec_addr_misaligned (odd_vec_addr_misaligned)
  );

endmodule
