`timescale 1ns / 1ps

// DP/EX pipeline register — dispatch dual-issue bundle latched before reservation stations.
module dp_ex
  import rv_dis_pkg::*;
(
  input  logic        clk,
  input  logic        rst_n,
  input  logic        enable,
  input  logic        flush,
  input  logic        stall,

  input  logic        i0_reg_write_disp,
  input  logic        i1_reg_write_disp,
  input  word_t       i0_pc_disp,
  input  word_t       i1_pc_disp,

  input  logic        ev0_enable_disp,
  input  opcode_t     ev0_opcode_disp,
  input  funct3_t     ev0_funct3_disp,
  input  funct7_t     ev0_funct7_disp,
  input  gpr_addr_t   ev0_rd_disp,
  input  gpr_addr_t   ev0_rs1_addr_disp,
  input  gpr_addr_t   ev0_rs2_addr_disp,
  input  word_t       ev0_imm_disp,
  input  word_t       ev0_rs1_data_disp,
  input  word_t       ev0_rs2_data_disp,
  input  word_t       ev0_pc_disp,

  input  logic        ev1_enable_disp,
  input  opcode_t     ev1_opcode_disp,
  input  funct3_t     ev1_funct3_disp,
  input  funct7_t     ev1_funct7_disp,
  input  gpr_addr_t   ev1_rd_disp,
  input  gpr_addr_t   ev1_rs1_addr_disp,
  input  gpr_addr_t   ev1_rs2_addr_disp,
  input  word_t       ev1_imm_disp,
  input  word_t       ev1_rs1_data_disp,
  input  word_t       ev1_rs2_data_disp,
  input  word_t       ev1_pc_disp,

  input  logic        od0_enable_disp,
  input  opcode_t     od0_opcode_disp,
  input  funct3_t     od0_funct3_disp,
  input  gpr_addr_t   od0_rd_disp,
  input  gpr_addr_t   od0_rs1_addr_disp,
  input  gpr_addr_t   od0_rs2_addr_disp,
  input  word_t       od0_imm_disp,
  input  word_t       od0_rs1_data_disp,
  input  word_t       od0_rs2_data_disp,
  input  word_t       od0_pc_disp,

  input  logic        od1_enable_disp,
  input  opcode_t     od1_opcode_disp,
  input  funct3_t     od1_funct3_disp,
  input  gpr_addr_t   od1_rd_disp,
  input  gpr_addr_t   od1_rs1_addr_disp,
  input  gpr_addr_t   od1_rs2_addr_disp,
  input  word_t       od1_imm_disp,
  input  word_t       od1_rs1_data_disp,
  input  word_t       od1_rs2_data_disp,
  input  word_t       od1_pc_disp,

  output logic        i0_reg_write_ex,
  output logic        i1_reg_write_ex,
  output word_t       i0_pc_ex,
  output word_t       i1_pc_ex,

  output logic        ev0_enable_ex,
  output opcode_t     ev0_opcode_ex,
  output funct3_t     ev0_funct3_ex,
  output funct7_t     ev0_funct7_ex,
  output gpr_addr_t   ev0_rd_ex,
  output gpr_addr_t   ev0_rs1_addr_ex,
  output gpr_addr_t   ev0_rs2_addr_ex,
  output word_t       ev0_imm_ex,
  output word_t       ev0_rs1_data_ex,
  output word_t       ev0_rs2_data_ex,
  output word_t       ev0_pc_ex,

  output logic        ev1_enable_ex,
  output opcode_t     ev1_opcode_ex,
  output funct3_t     ev1_funct3_ex,
  output funct7_t     ev1_funct7_ex,
  output gpr_addr_t   ev1_rd_ex,
  output gpr_addr_t   ev1_rs1_addr_ex,
  output gpr_addr_t   ev1_rs2_addr_ex,
  output word_t       ev1_imm_ex,
  output word_t       ev1_rs1_data_ex,
  output word_t       ev1_rs2_data_ex,
  output word_t       ev1_pc_ex,

  output logic        od0_enable_ex,
  output opcode_t     od0_opcode_ex,
  output funct3_t     od0_funct3_ex,
  output gpr_addr_t   od0_rd_ex,
  output gpr_addr_t   od0_rs1_addr_ex,
  output gpr_addr_t   od0_rs2_addr_ex,
  output word_t       od0_imm_ex,
  output word_t       od0_rs1_data_ex,
  output word_t       od0_rs2_data_ex,
  output word_t       od0_pc_ex,

  output logic        od1_enable_ex,
  output opcode_t     od1_opcode_ex,
  output funct3_t     od1_funct3_ex,
  output gpr_addr_t   od1_rd_ex,
  output gpr_addr_t   od1_rs1_addr_ex,
  output gpr_addr_t   od1_rs2_addr_ex,
  output word_t       od1_imm_ex,
  output word_t       od1_rs1_data_ex,
  output word_t       od1_rs2_data_ex,
  output word_t       od1_pc_ex
);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      i0_reg_write_ex <= 1'b0;
      i1_reg_write_ex <= 1'b0;
      i0_pc_ex        <= '0;
      i1_pc_ex        <= '0;
      ev0_enable_ex   <= 1'b0;
      ev0_opcode_ex   <= '0;
      ev0_funct3_ex   <= '0;
      ev0_funct7_ex   <= '0;
      ev0_rd_ex       <= '0;
      ev0_rs1_addr_ex <= '0;
      ev0_rs2_addr_ex <= '0;
      ev0_imm_ex      <= '0;
      ev0_rs1_data_ex <= '0;
      ev0_rs2_data_ex <= '0;
      ev0_pc_ex       <= '0;
      ev1_enable_ex   <= 1'b0;
      ev1_opcode_ex   <= '0;
      ev1_funct3_ex   <= '0;
      ev1_funct7_ex   <= '0;
      ev1_rd_ex       <= '0;
      ev1_rs1_addr_ex <= '0;
      ev1_rs2_addr_ex <= '0;
      ev1_imm_ex      <= '0;
      ev1_rs1_data_ex <= '0;
      ev1_rs2_data_ex <= '0;
      ev1_pc_ex       <= '0;
      od0_enable_ex   <= 1'b0;
      od0_opcode_ex   <= '0;
      od0_funct3_ex   <= '0;
      od0_rd_ex       <= '0;
      od0_rs1_addr_ex <= '0;
      od0_rs2_addr_ex <= '0;
      od0_imm_ex      <= '0;
      od0_rs1_data_ex <= '0;
      od0_rs2_data_ex <= '0;
      od0_pc_ex       <= '0;
      od1_enable_ex   <= 1'b0;
      od1_opcode_ex   <= '0;
      od1_funct3_ex   <= '0;
      od1_rd_ex       <= '0;
      od1_rs1_addr_ex <= '0;
      od1_rs2_addr_ex <= '0;
      od1_imm_ex      <= '0;
      od1_rs1_data_ex <= '0;
      od1_rs2_data_ex <= '0;
      od1_pc_ex       <= '0;
    end else if (flush) begin
      i0_reg_write_ex <= 1'b0;
      i1_reg_write_ex <= 1'b0;
      i0_pc_ex        <= '0;
      i1_pc_ex        <= '0;
      ev0_enable_ex   <= 1'b0;
      ev0_opcode_ex   <= '0;
      ev0_funct3_ex   <= '0;
      ev0_funct7_ex   <= '0;
      ev0_rd_ex       <= '0;
      ev0_rs1_addr_ex <= '0;
      ev0_rs2_addr_ex <= '0;
      ev0_imm_ex      <= '0;
      ev0_rs1_data_ex <= '0;
      ev0_rs2_data_ex <= '0;
      ev0_pc_ex       <= '0;
      ev1_enable_ex   <= 1'b0;
      ev1_opcode_ex   <= '0;
      ev1_funct3_ex   <= '0;
      ev1_funct7_ex   <= '0;
      ev1_rd_ex       <= '0;
      ev1_rs1_addr_ex <= '0;
      ev1_rs2_addr_ex <= '0;
      ev1_imm_ex      <= '0;
      ev1_rs1_data_ex <= '0;
      ev1_rs2_data_ex <= '0;
      ev1_pc_ex       <= '0;
      od0_enable_ex   <= 1'b0;
      od0_opcode_ex   <= '0;
      od0_funct3_ex   <= '0;
      od0_rd_ex       <= '0;
      od0_rs1_addr_ex <= '0;
      od0_rs2_addr_ex <= '0;
      od0_imm_ex      <= '0;
      od0_rs1_data_ex <= '0;
      od0_rs2_data_ex <= '0;
      od0_pc_ex       <= '0;
      od1_enable_ex   <= 1'b0;
      od1_opcode_ex   <= '0;
      od1_funct3_ex   <= '0;
      od1_rd_ex       <= '0;
      od1_rs1_addr_ex <= '0;
      od1_rs2_addr_ex <= '0;
      od1_imm_ex      <= '0;
      od1_rs1_data_ex <= '0;
      od1_rs2_data_ex <= '0;
      od1_pc_ex       <= '0;
    end else if (enable && !stall) begin
      i0_reg_write_ex <= i0_reg_write_disp;
      i1_reg_write_ex <= i1_reg_write_disp;
      i0_pc_ex        <= i0_pc_disp;
      i1_pc_ex        <= i1_pc_disp;
      ev0_enable_ex   <= ev0_enable_disp;
      ev0_opcode_ex   <= ev0_opcode_disp;
      ev0_funct3_ex   <= ev0_funct3_disp;
      ev0_funct7_ex   <= ev0_funct7_disp;
      ev0_rd_ex       <= ev0_rd_disp;
      ev0_rs1_addr_ex <= ev0_rs1_addr_disp;
      ev0_rs2_addr_ex <= ev0_rs2_addr_disp;
      ev0_imm_ex      <= ev0_imm_disp;
      ev0_rs1_data_ex <= ev0_rs1_data_disp;
      ev0_rs2_data_ex <= ev0_rs2_data_disp;
      ev0_pc_ex       <= ev0_pc_disp;
      ev1_enable_ex   <= ev1_enable_disp;
      ev1_opcode_ex   <= ev1_opcode_disp;
      ev1_funct3_ex   <= ev1_funct3_disp;
      ev1_funct7_ex   <= ev1_funct7_disp;
      ev1_rd_ex       <= ev1_rd_disp;
      ev1_rs1_addr_ex <= ev1_rs1_addr_disp;
      ev1_rs2_addr_ex <= ev1_rs2_addr_disp;
      ev1_imm_ex      <= ev1_imm_disp;
      ev1_rs1_data_ex <= ev1_rs1_data_disp;
      ev1_rs2_data_ex <= ev1_rs2_data_disp;
      ev1_pc_ex       <= ev1_pc_disp;
      od0_enable_ex   <= od0_enable_disp;
      od0_opcode_ex   <= od0_opcode_disp;
      od0_funct3_ex   <= od0_funct3_disp;
      od0_rd_ex       <= od0_rd_disp;
      od0_rs1_addr_ex <= od0_rs1_addr_disp;
      od0_rs2_addr_ex <= od0_rs2_addr_disp;
      od0_imm_ex      <= od0_imm_disp;
      od0_rs1_data_ex <= od0_rs1_data_disp;
      od0_rs2_data_ex <= od0_rs2_data_disp;
      od0_pc_ex       <= od0_pc_disp;
      od1_enable_ex   <= od1_enable_disp;
      od1_opcode_ex   <= od1_opcode_disp;
      od1_funct3_ex   <= od1_funct3_disp;
      od1_rd_ex       <= od1_rd_disp;
      od1_rs1_addr_ex <= od1_rs1_addr_disp;
      od1_rs2_addr_ex <= od1_rs2_addr_disp;
      od1_imm_ex      <= od1_imm_disp;
      od1_rs1_data_ex <= od1_rs1_data_disp;
      od1_rs2_data_ex <= od1_rs2_data_disp;
      od1_pc_ex       <= od1_pc_disp;
    end
  end

endmodule
